### ISSUE TITLE
Add proxy feature

### ISSUE THREAD

**Issue by AliAlmasi** [davegallant/vpngate#126]
As an Iranian internet user who faces internet censorship everyday, VPNGate and this tool comes in handy, but in countries like Iran, the VPNGate domain is filtered (firewalled) and you can't access this website if you don't use any VPN or Proxy or whatever (however, VPNGate mirrors are pretty good and they work best in Iran).

I wanted to use this tool but then I realized this tool cannot be used if the client doesn't set environment proxy on his/her machine, then I thought maybe it'll be a good idea if this tool use the proxy server (can be given to the program via command flags or something) and then fetch the servers from VPNGate.

I really like this project and I wanted to contribute and add this feature to it, but unfortunately, I'm not familiar with Go.

**Comment by davegallant** [comment]
@AliAlmasi this is a good idea. What do you think about having a `--socks5` flag that would allow for a SOCKS5 proxy server to be used when making any http client connections to fetch the list of servers?

**Comment by davegallant** [comment]
I've also added a `--proxy` flag to support HTTP/HTTPS. See https://github.com/davegallant/vpngate/pull/127

**Comment by AliAlmasi** [comment]
> @AliAlmasi this is a good idea. What do you think about having a `--socks5` flag that would allow for a SOCKS5 proxy server to be used when making any http client connections to fetch the list of servers?

Yeah, Socks5 proxy would be great because a lot censorship circumvent programs (such as V2Ray, Hiddify and Oblivion) support  Socks5 connections.

> I've also added a --proxy flag to support HTTP/HTTPS. See https://github.com/davegallant/vpngate/pull/127

Http and Https proxies can fix the problem. At least it's better than nothing haha. Thanks a bunch.

**Comment by davegallant** [comment]
Released in https://github.com/davegallant/vpngate/releases/tag/v0.2.0.
