### ISSUE TITLE
Error: davegallant/public/vpngate: wrong number of arguments (given 1, expected 0)

### ISSUE THREAD

**Issue by HLFH** [davegallant/vpngate#83]
Hello,

After brew install davegallant/public/vpngate

I get this error:
Error: davegallant/public/vpngate: wrong number of arguments (given 1, expected 0)

Any ideas? Thanks

**Comment by davegallant** [comment]
Hey. Sorry for the delay. Had been tuning my github notifications and missed this.

It should work again with the latest release ([v0.1.2](https://github.com/davegallant/vpngate/releases/tag/v0.1.2)).
