### ISSUE TITLE
 FTL unable to parse vpn list: Unable to parse CSV: parse error on line 51

### ISSUE THREAD

**Issue by laobulang** [davegallant/vpngate#96]
./vpngate list
2:35AM INF The vpn server list cache has expired
2:35AM INF Fetching the latest server list
2:35AM FTL unable to parse vpn list: Unable to parse CSV: parse error on line 51, column 116: bare " in non-quoted-field

**Comment by davegallant** [comment]
This should be fixed now in [v0.0.15](https://github.com/davegallant/vpngate/releases/tag/v0.0.15).

Also added retries for additional robustness.
